version: "3.9"
services:
  vdcore:
    image: "360deg/vdcore"
    ports: 
      - 5228:80
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
    environment:
      # CORE CONNECTION
      - ConnectionStrings__VDCoreConnection=server=mariadb;user id=root;password=root;database=vdcore; # do NOT change db name, otherwise there will be errors
      # SWAGGER (true/false) | default = true
      - EnableSwagger=true
    
  mariadb:
    image: "mariadb:10.1.48"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_USER: "root_user"
    volumes:
      - ./maria-data:/var/lib/mysql